import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import type { DatabaseSync } from 'node:sqlite';
import { after, describe, test } from 'node:test';

import { leastSquares, solveRates, type Observation } from '../src/pricing/solve.ts';
import { openDb } from '../src/store/db.ts';
import { registerProject } from '../src/store/projects.ts';

describe('leastSquares', () => {
  test('recovers exact coefficients from noise-free observations', () => {
    // cost = 2*a + 10*b + 0.2*c
    const truth = [2, 10, 0.2];
    const obs: Observation[] = [
      [1, 0.5, 100],
      [3, 2, 250],
      [0.2, 4, 900],
      [7, 1, 40],
      [5, 3, 600],
    ].map((x) => ({ x, y: x.reduce((s, xi, i) => s + xi * truth[i]!, 0) }));

    const solved = leastSquares(obs, 3);
    assert.ok(solved);
    for (const [i, expected] of truth.entries()) {
      assert.ok(Math.abs(solved[i]! - expected) < 1e-9, `term ${i}: ${solved[i]} != ${expected}`);
    }
  });

  test('is robust to noise, returning coefficients close to the truth', () => {
    const truth = [3, 15];
    const obs: Observation[] = Array.from({ length: 200 }, (_, i) => {
      const x = [1 + (i % 17), 0.5 + (i % 7) / 3];
      const clean = x.reduce((s, xi, k) => s + xi * truth[k]!, 0);
      // Deterministic pseudo-noise, about a percent.
      return { x, y: clean * (1 + 0.01 * Math.sin(i)) };
    });

    const solved = leastSquares(obs, 2);
    assert.ok(solved);
    assert.ok(Math.abs(solved[0]! - 3) < 0.1, `input rate drifted: ${solved[0]}`);
    assert.ok(Math.abs(solved[1]! - 15) < 0.1, `output rate drifted: ${solved[1]}`);
  });

  test('returns null rather than a wrong answer when there are too few observations', () => {
    assert.equal(leastSquares([{ x: [1, 2, 3], y: 6 }], 3), null);
  });

  test('returns null when columns do not vary independently', () => {
    // The second column is always twice the first: the system is singular, and
    // this is the case that made haiku unsolvable against real data.
    const obs: Observation[] = [1, 2, 3, 4, 5, 6].map((v) => ({ x: [v, v * 2], y: v * 7 }));
    assert.equal(leastSquares(obs, 2), null);
  });
});


const solveDbs: { dir: string; db: DatabaseSync }[] = [];
after(() => {
  for (const { dir, db } of solveDbs) {
    try { db.close(); } catch { /* already closed */ }
    try { fs.rmSync(dir, { recursive: true, force: true }); } catch { /* windows handle */ }
  }
});

/**
 * Build a project whose billing was generated by known rates, so the solver's
 * answer can be checked against the truth rather than against itself.
 */
function billedProject(rates: { input: number; output: number; write: number; read: number }) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'tokenviz-solve-'));
  const db = openDb(path.join(dir, 'store.sqlite'));
  solveDbs.push({ dir, db });
  const project = registerProject(db, { rootPath: path.join(dir, 'repo') });
  const model = 'm';

  for (let i = 0; i < 30; i++) {
    // Vary the categories independently so the system is not singular.
    const input = 1000 * (1 + (i % 5));
    const output = 100_000 * (1 + (i % 7));
    const write = 500_000 * (1 + (i % 3));
    const read = 20_000_000 * (1 + (i % 11));
    const cost =
      (input * rates.input + output * rates.output + write * rates.write + read * rates.read) / 1e6;
    db.prepare(
      `INSERT INTO session_model_cost (project_id, session, model, input, output, thinking,
         cache_read, cache_write, cost_usd, observed_at)
       VALUES (?, ?, ?, ?, ?, 0, ?, ?, ?, '2026-09-01T00:00:00Z')`,
    ).run(project.id, `s${i}`, model, input, output, read, write, cost);

    // Request rows supply the 5m/1h tier mix. All 1h here, so the blend is 2x.
    db.prepare(
      `INSERT INTO request (project_id, message_id, session, slot, origin, model, ts, day,
         input, cache_write, cache_write_5m, cache_write_1h, cache_read, output, thinking,
         iterations, service_tier, cwd, first_seen_at)
       VALUES (?, ?, ?, 'main', 'console', ?, '2026-09-01T00:00:00Z', '2026-09-01',
         ?, ?, 0, ?, ?, ?, 0, 0, NULL, NULL, '2026-09-01T00:00:00Z')`,
    ).run(project.id, `r${i}`, `s${i}`, model, input, write, write, read, output);
  }
  return { db, project };
}

describe('solveRates', () => {
  test('recovers a card whose cache read is the usual tenth of input', () => {
    // input 4, so read 0.4 and a 1h write 8.
    const { db, project } = billedProject({ input: 4, output: 20, write: 8, read: 0.4 });
    const [solved] = solveRates(db, project);
    assert.ok(solved?.rates);
    assert.equal(solved.corroborated, true, 'both derivations of input agree');
    assert.ok(Math.abs(solved.rates.inputPerMTok - 4) < 0.05, `input ${solved.rates.inputPerMTok}`);
    assert.ok(Math.abs(solved.rates.outputPerMTok - 20) < 0.05);
    assert.ok(Math.abs(solved.rates.cacheReadPerMTok - 0.4) < 0.01);
  });

  test('a model pricing cache reads unusually is still priced, from its write rate', () => {
    // Fable 5.1's shape: base 10, 1h write 20, but reads at a fortieth, not a tenth.
    const { db, project } = billedProject({ input: 10, output: 50, write: 20, read: 0.25 });
    const [solved] = solveRates(db, project);
    assert.ok(solved?.rates);
    assert.equal(solved.corroborated, false, 'the two derivations disagree, and that is reported');
    assert.match(solved.note ?? '', /cache reads at 1\//);
    // Derived from the write rate, not from 10x the read rate, which would give 2.5.
    assert.ok(Math.abs(solved.rates.inputPerMTok - 10) < 0.2, `input ${solved.rates.inputPerMTok}`);
    assert.ok(Math.abs(solved.rates.cacheReadPerMTok - 0.25) < 0.01, 'the fitted read rate is kept');
  });

  test('the fitted rates reproduce the billing they were derived from', () => {
    const { db, project } = billedProject({ input: 10, output: 50, write: 20, read: 0.25 });
    const [solved] = solveRates(db, project);
    assert.ok(solved && solved.medianRelError < 0.01, `median error ${solved?.medianRelError}`);
  });
});
